spring:
  application:
    name: cooperative-voting-api
  datasource:
    url: jdbc:postgresql://localhost:5432/cooperative_voting
    username: cooperative_voting
    password: cooperative_voting
  jpa:
    hibernate:
      ddl-auto: validate

votacao:
  sessao:
    duracao-padrao-segundos: 60
    duracao-minima-segundos: 5

integracao:
  random-org:
    base-url: "https://www.random.org/integers/?num=1&min=0&max=1&col=1&base=10&format=plain&rnd=new"
    connect-timeout-millis: 2000
    read-timeout-millis: 2000

springdoc:
  swagger-ui:
    url: /openapi.yaml
